#!make

help:
	@echo ""
	@echo "Usage:"
	@echo ""
	@echo "Setup, build and run (Docker):"
	@echo "  make docker-start          					Start the server and database docker containers"
	@echo "  make docker-stop          					Stop the server and database docker containers"
	@echo "  make docker-build						Build the docker containers"
	@echo "  make docker-start-web  					Start the server on a docker container"
	@echo "  make docker-stop-web   					Stop the server docker container"
	@echo "  make docker-start-db   					Start a database instance on a docker container"
	@echo "  make docker-stop-db    					Stop the database docker container"
	@echo ""
	@echo "Setup, build and run:"
	@echo "  make setup-dev						Setup the project including development dependencies"
	@echo "  make clean-setup-dev						Setup the project including development dependencies, cleaning all previous installed dependencies"
	@echo "  make clean-setup						Setup the project, cleaning all previous installed dependencies"
	@echo "  make build  	        					Compile the project typescript and generate the output bundles"
	@echo "  make start							Execute the builded code"
	@echo "  make dev							Start the server in development mode"
	@echo "  make setup-local-nodejs-env					Setup local development environment file"
	@echo "  make setup-local-nodejs-env-test					Setup local testing environment file"
	@echo ""
	@echo "Migrations and Seeds:"	
	@echo "  make migration-run        					Run the migrations"
	@echo "  make migration-revert       					Revert the migrations"
	@echo "  make migration-generate NAME={migration_name} 		Generate a new migration based on entities changes"
	@echo "  make docker-run-migration-run        				Run the migrations on the Node JS Docker container"
	@echo "  make docker-run-migration-revert       			Revert the migrations on the Node JS Docker container"
	@echo "  make docker-run-migration-generate NAME={migration_name} 	Generate a new migration based on entities changes on the Node JS Docker container"
	@echo ""
	@echo "Code Quality:"	
	@echo "  make lint  	         					Run the server linter"
	@echo "  make lint-fix  	         				Run the server linter with autofix flag activated"
	@echo "  make format-code        					Format the server code with prettier"
	@echo "  make test  	         					Run the server tests"
	@echo "  make coverage-test        					Run the server tests with code coverage"
	@echo ""
	@echo "Others:"
	@echo "  make docs          						Shows documentation"
	@echo ""